import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import "@/styles/globals.css";
import { ContextProvider } from "../utils/context";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { AuthContextProvider } from "@/utils/authContext";
import Head from "next/head";

export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>E-commerce website</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ContextProvider>
        <AuthContextProvider>
          <Navbar />
          <div className="pt-[8vh] min-h-[94vh]">
            <Component {...pageProps} />
            <ToastContainer />
          </div>
          <Footer />
        </AuthContextProvider>
      </ContextProvider>
    </>
  );
}
